### PR TITLE
Factorize checkfile to cmdutils.js and test it.

### PR DESCRIPTION
**Pull request by blambeau**
Hey @znerol,

This pull request factorizes `checkfile` to reuse & test it.

For the record, the binaries in bin are currently broken on my node.js installation, for two reasons at least:

* `path.existsSync` needs to be replaced by `fs.existsSync` (done in this commit)
* `process.ARGV` needs to be replaced by `process.argv` (is that an expected change in the node.js world?)

I think that factorizing parts and testing them is probably the way to go, right?

### CODE REVIEW

**Comment by znerol** [comment]
Thanks a lot. Truly makes a lot of sense.

**Comment by znerol** [comment]
Also pushed a fix for the `process.argv` problem.

**Comment by znerol** [comment]
Oh, just noticed that `yield` is a reserved word. Replaced it with `invoked` in the test (2b171a9).

**Comment by blambeau** [comment]
Sorry about that, did not know yield was reserved in javascript/node.

**Pull request merged**
